apiVersion: apps/v1
kind: Deployment
metadata:
  name: chait
  labels:
     app: front
spec:
  replicas: 3
  selector:
     matchLabels:
      dev: test
  template:
    metadata:
      labels:
        dev: test
    spec:   
     containers:
      - name: cont
        image: chumaedeogu/peter
        ports:
        - containerPort: 1991
        