apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
  labels:
     app: front
spec:
  replicas: 2
  selector:
    matchLabels:
        env: chatpod
  template:
     metadata:
       labels:
        env: chatpod
     spec:
        containers:
          - name: app1
            image: chumaedeogu/chatai
            ports:
              - containerPort: 8501
            resources:
              requests:
                cpu: "1"
                memory: "1"
              limits:
                cpu: "2"
                memory: "2" 
   