pipeline {
    agent any

    environment {
        SONAR_HOME = tool('sonar-scanner')
    }

    stages {
        stage("Static Code Analysis") {
            steps {
                withSonarQubeEnv('sonar-scanner') {  // Ensure 'sonarqube' matches Jenkins config
                    bat """
                        "%SONAR_HOME%\\bin\\sonar-scanner" ^
                        -Dsonar.projectName="chatai" ^
                        -Dsonar.projectKey="chatai"
                    """
                }
            }
        }

        stage("Wait for Quality Gate") {
            steps {
                script {
                    def qg = waitForQualityGate(abortPipeline: true)
                    if (qg.status != 'OK') {
                        error "Pipeline failed due to Quality Gate status: ${qg.status}"
                    }
                }
            }
        }
        stage("buiid the image"){
            steps{
                bat "docker build -t peter:${BUILD_NUMBER} ."
            }
        }
        
        stage('Update Image') {
            steps {
                script {
                    // Define the new image
                    // Update the image in the deployment.yaml file
                    sh """
                        sed -i 's|image: .*|image: chumaedeogu/peter:${BUILD_NUMBER}|g' new8ks/chai.yml
                     """
                }
            }
        }


 
    }
}
