pipeline {
    agent any

    environment {
        SONAR_HOME = tool('sonar-scanner')
    }

    stages {
        stage("Static Code Analysis") {
            steps {
                withSonarQubeEnv('sonar-scanner') {  // Ensure 'sonarqube' matches Jenkins config
                    bat """
                        "%SONAR_HOME%\\bin\\sonar-scanner" ^
                        -Dsonar.projectName="chatai" ^
                        -Dsonar.projectKey="chatai"
                    """
                }
            }
        }

        stage("Wait for Quality Gate") {
            steps {
                script {
                    def qg = waitForQualityGate(abortPipeline: true)
                    if (qg.status != 'OK') {
                        error "Pipeline failed due to Quality Gate status: ${qg.status}"
                    }
                }
            }
        }
        stage("buiid the image"){
            steps{
                bat "docker build -t peter:${build_number} ."
            }
        }
        stage(update the image number){
            steps{
                script{
                    bat '''
                    "C:\\Program Files\\Git\\git-bash.exe" --cd-to-home "/home/chuma/projects/chatai/new8ks/updatedep.sh"

                    '''
                }
            }
        }

 
    }
}
