apiVersion: v1
kind: Service
metadata:
  name: chataiapp-svc
  namespace: demo-test
spec:
  selector:
    app: chataiapp
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
  type: NodePort
